<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="foodapp" nsURI="http://www.rm2pt.com/foodapp" nsPrefix="foodapp">
  <eClassifiers xsi:type="ecore:EClass" name="UserBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerService" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="restaurantmanager" eType="#//RestaurantManager"
        eOpposite="#//RestaurantManager/customerservice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliverydriver" eType="#//DeliveryDriver"
        eOpposite="#//DeliveryDriver/customerservice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer"
        eOpposite="#//Customer/customerservice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliveryDriver" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customerservice" eType="#//CustomerService"
        eOpposite="#//CustomerService/deliverydriver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer"
        eOpposite="#//Customer/deliverydriver"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestaurantManager" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cuisine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customerservice" eType="#//CustomerService"
        eOpposite="#//CustomerService/restaurantmanager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customerservice" eType="#//CustomerService"
        eOpposite="#//CustomerService/customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliverydriver" eType="#//DeliveryDriver"
        eOpposite="#//DeliveryDriver/customer"/>
  </eClassifiers>
</ecore:EPackage>
