/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.foodapp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class UserBaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.UserBase");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUserBaseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUserBaseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUsersKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cUsersAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cUsersUserParserRuleCall_3_2_0 = (RuleCall)cUsersAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cUsersAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cUsersUserParserRuleCall_3_3_1_0 = (RuleCall)cUsersAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//UserBase returns UserBase:
		//    {UserBase}
		//    'UserBase'
		//    '{'
		//        ('users' '{' users+=User ( "," users+=User)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{UserBase}
		//'UserBase'
		//'{'
		//    ('users' '{' users+=User ( "," users+=User)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{UserBase}
		public Action getUserBaseAction_0() { return cUserBaseAction_0; }
		
		//'UserBase'
		public Keyword getUserBaseKeyword_1() { return cUserBaseKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('users' '{' users+=User ( "," users+=User)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'users'
		public Keyword getUsersKeyword_3_0() { return cUsersKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//users+=User
		public Assignment getUsersAssignment_3_2() { return cUsersAssignment_3_2; }
		
		//User
		public RuleCall getUsersUserParserRuleCall_3_2_0() { return cUsersUserParserRuleCall_3_2_0; }
		
		//( "," users+=User)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//users+=User
		public Assignment getUsersAssignment_3_3_1() { return cUsersAssignment_3_3_1; }
		
		//User
		public RuleCall getUsersUserParserRuleCall_3_3_1_0() { return cUsersUserParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.User");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCustomerServiceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDeliveryDriverParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRestaurantManagerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCustomerParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//User returns User:
		//    CustomerService | DeliveryDriver | RestaurantManager | Customer;
		@Override public ParserRule getRule() { return rule; }
		
		//CustomerService | DeliveryDriver | RestaurantManager | Customer
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CustomerService
		public RuleCall getCustomerServiceParserRuleCall_0() { return cCustomerServiceParserRuleCall_0; }
		
		//DeliveryDriver
		public RuleCall getDeliveryDriverParserRuleCall_1() { return cDeliveryDriverParserRuleCall_1; }
		
		//RestaurantManager
		public RuleCall getRestaurantManagerParserRuleCall_2() { return cRestaurantManagerParserRuleCall_2; }
		
		//Customer
		public RuleCall getCustomerParserRuleCall_3() { return cCustomerParserRuleCall_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class CustomerServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.CustomerService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCustomerServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCustomerServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsernameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUsernameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUsernameEStringParserRuleCall_4_1_0 = (RuleCall)cUsernameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPasswordKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPasswordAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_5_1_0 = (RuleCall)cPasswordAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIdAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_6_1_0 = (RuleCall)cIdAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhoneNumberKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhoneNumberAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhoneNumberEStringParserRuleCall_7_1_0 = (RuleCall)cPhoneNumberAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cRestaurantmanagerKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cRestaurantmanagerAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cRestaurantmanagerRestaurantManagerCrossReference_8_1_0 = (CrossReference)cRestaurantmanagerAssignment_8_1.eContents().get(0);
		private final RuleCall cRestaurantmanagerRestaurantManagerEStringParserRuleCall_8_1_0_1 = (RuleCall)cRestaurantmanagerRestaurantManagerCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cDeliverydriverKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cDeliverydriverAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cDeliverydriverDeliveryDriverCrossReference_9_1_0 = (CrossReference)cDeliverydriverAssignment_9_1.eContents().get(0);
		private final RuleCall cDeliverydriverDeliveryDriverEStringParserRuleCall_9_1_0_1 = (RuleCall)cDeliverydriverDeliveryDriverCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCustomerKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCustomerAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cCustomerCustomerCrossReference_10_1_0 = (CrossReference)cCustomerAssignment_10_1.eContents().get(0);
		private final RuleCall cCustomerCustomerEStringParserRuleCall_10_1_0_1 = (RuleCall)cCustomerCustomerCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//CustomerService returns CustomerService:
		//    {CustomerService}
		//    'CustomerService'
		//    name=EString
		//    '{'
		//        ('username' username=EString)?
		//        ('password' password=EString)?
		//        ('id' id=EInt)?
		//        ('phoneNumber' phoneNumber=EString)?
		//        ('restaurantmanager' restaurantmanager=[RestaurantManager|EString])?
		//        ('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
		//        ('customer' customer=[Customer|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{CustomerService}
		//'CustomerService'
		//name=EString
		//'{'
		//    ('username' username=EString)?
		//    ('password' password=EString)?
		//    ('id' id=EInt)?
		//    ('phoneNumber' phoneNumber=EString)?
		//    ('restaurantmanager' restaurantmanager=[RestaurantManager|EString])?
		//    ('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
		//    ('customer' customer=[Customer|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{CustomerService}
		public Action getCustomerServiceAction_0() { return cCustomerServiceAction_0; }
		
		//'CustomerService'
		public Keyword getCustomerServiceKeyword_1() { return cCustomerServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('username' username=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'username'
		public Keyword getUsernameKeyword_4_0() { return cUsernameKeyword_4_0; }
		
		//username=EString
		public Assignment getUsernameAssignment_4_1() { return cUsernameAssignment_4_1; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_4_1_0() { return cUsernameEStringParserRuleCall_4_1_0; }
		
		//('password' password=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'password'
		public Keyword getPasswordKeyword_5_0() { return cPasswordKeyword_5_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_5_1() { return cPasswordAssignment_5_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_5_1_0() { return cPasswordEStringParserRuleCall_5_1_0; }
		
		//('id' id=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'id'
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }
		
		//id=EInt
		public Assignment getIdAssignment_6_1() { return cIdAssignment_6_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_6_1_0() { return cIdEIntParserRuleCall_6_1_0; }
		
		//('phoneNumber' phoneNumber=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'phoneNumber'
		public Keyword getPhoneNumberKeyword_7_0() { return cPhoneNumberKeyword_7_0; }
		
		//phoneNumber=EString
		public Assignment getPhoneNumberAssignment_7_1() { return cPhoneNumberAssignment_7_1; }
		
		//EString
		public RuleCall getPhoneNumberEStringParserRuleCall_7_1_0() { return cPhoneNumberEStringParserRuleCall_7_1_0; }
		
		//('restaurantmanager' restaurantmanager=[RestaurantManager|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'restaurantmanager'
		public Keyword getRestaurantmanagerKeyword_8_0() { return cRestaurantmanagerKeyword_8_0; }
		
		//restaurantmanager=[RestaurantManager|EString]
		public Assignment getRestaurantmanagerAssignment_8_1() { return cRestaurantmanagerAssignment_8_1; }
		
		//[RestaurantManager|EString]
		public CrossReference getRestaurantmanagerRestaurantManagerCrossReference_8_1_0() { return cRestaurantmanagerRestaurantManagerCrossReference_8_1_0; }
		
		//EString
		public RuleCall getRestaurantmanagerRestaurantManagerEStringParserRuleCall_8_1_0_1() { return cRestaurantmanagerRestaurantManagerEStringParserRuleCall_8_1_0_1; }
		
		//('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'deliverydriver'
		public Keyword getDeliverydriverKeyword_9_0() { return cDeliverydriverKeyword_9_0; }
		
		//deliverydriver=[DeliveryDriver|EString]
		public Assignment getDeliverydriverAssignment_9_1() { return cDeliverydriverAssignment_9_1; }
		
		//[DeliveryDriver|EString]
		public CrossReference getDeliverydriverDeliveryDriverCrossReference_9_1_0() { return cDeliverydriverDeliveryDriverCrossReference_9_1_0; }
		
		//EString
		public RuleCall getDeliverydriverDeliveryDriverEStringParserRuleCall_9_1_0_1() { return cDeliverydriverDeliveryDriverEStringParserRuleCall_9_1_0_1; }
		
		//('customer' customer=[Customer|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'customer'
		public Keyword getCustomerKeyword_10_0() { return cCustomerKeyword_10_0; }
		
		//customer=[Customer|EString]
		public Assignment getCustomerAssignment_10_1() { return cCustomerAssignment_10_1; }
		
		//[Customer|EString]
		public CrossReference getCustomerCustomerCrossReference_10_1_0() { return cCustomerCustomerCrossReference_10_1_0; }
		
		//EString
		public RuleCall getCustomerCustomerEStringParserRuleCall_10_1_0_1() { return cCustomerCustomerEStringParserRuleCall_10_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class DeliveryDriverElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.DeliveryDriver");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDeliveryDriverAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDeliveryDriverKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsernameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUsernameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUsernameEStringParserRuleCall_4_1_0 = (RuleCall)cUsernameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPasswordKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPasswordAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_5_1_0 = (RuleCall)cPasswordAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIdAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_6_1_0 = (RuleCall)cIdAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhoneNumberKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhoneNumberAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhoneNumberEStringParserRuleCall_7_1_0 = (RuleCall)cPhoneNumberAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cVehicleNumberKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cVehicleNumberAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cVehicleNumberEStringParserRuleCall_8_1_0 = (RuleCall)cVehicleNumberAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cVehicleTypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cVehicleTypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cVehicleTypeEStringParserRuleCall_9_1_0 = (RuleCall)cVehicleTypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCustomerserviceKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCustomerserviceAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cCustomerserviceCustomerServiceCrossReference_10_1_0 = (CrossReference)cCustomerserviceAssignment_10_1.eContents().get(0);
		private final RuleCall cCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1 = (RuleCall)cCustomerserviceCustomerServiceCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCustomerKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cCustomerAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cCustomerCustomerCrossReference_11_1_0 = (CrossReference)cCustomerAssignment_11_1.eContents().get(0);
		private final RuleCall cCustomerCustomerEStringParserRuleCall_11_1_0_1 = (RuleCall)cCustomerCustomerCrossReference_11_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//DeliveryDriver returns DeliveryDriver:
		//    {DeliveryDriver}
		//    'DeliveryDriver'
		//    name=EString
		//    '{'
		//        ('username' username=EString)?
		//        ('password' password=EString)?
		//        ('id' id=EInt)?
		//        ('phoneNumber' phoneNumber=EString)?
		//        ('vehicleNumber' vehicleNumber=EString)?
		//        ('vehicleType' vehicleType=EString)?
		//        ('customerservice' customerservice=[CustomerService|EString])?
		//        ('customer' customer=[Customer|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DeliveryDriver}
		//'DeliveryDriver'
		//name=EString
		//'{'
		//    ('username' username=EString)?
		//    ('password' password=EString)?
		//    ('id' id=EInt)?
		//    ('phoneNumber' phoneNumber=EString)?
		//    ('vehicleNumber' vehicleNumber=EString)?
		//    ('vehicleType' vehicleType=EString)?
		//    ('customerservice' customerservice=[CustomerService|EString])?
		//    ('customer' customer=[Customer|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{DeliveryDriver}
		public Action getDeliveryDriverAction_0() { return cDeliveryDriverAction_0; }
		
		//'DeliveryDriver'
		public Keyword getDeliveryDriverKeyword_1() { return cDeliveryDriverKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('username' username=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'username'
		public Keyword getUsernameKeyword_4_0() { return cUsernameKeyword_4_0; }
		
		//username=EString
		public Assignment getUsernameAssignment_4_1() { return cUsernameAssignment_4_1; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_4_1_0() { return cUsernameEStringParserRuleCall_4_1_0; }
		
		//('password' password=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'password'
		public Keyword getPasswordKeyword_5_0() { return cPasswordKeyword_5_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_5_1() { return cPasswordAssignment_5_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_5_1_0() { return cPasswordEStringParserRuleCall_5_1_0; }
		
		//('id' id=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'id'
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }
		
		//id=EInt
		public Assignment getIdAssignment_6_1() { return cIdAssignment_6_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_6_1_0() { return cIdEIntParserRuleCall_6_1_0; }
		
		//('phoneNumber' phoneNumber=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'phoneNumber'
		public Keyword getPhoneNumberKeyword_7_0() { return cPhoneNumberKeyword_7_0; }
		
		//phoneNumber=EString
		public Assignment getPhoneNumberAssignment_7_1() { return cPhoneNumberAssignment_7_1; }
		
		//EString
		public RuleCall getPhoneNumberEStringParserRuleCall_7_1_0() { return cPhoneNumberEStringParserRuleCall_7_1_0; }
		
		//('vehicleNumber' vehicleNumber=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'vehicleNumber'
		public Keyword getVehicleNumberKeyword_8_0() { return cVehicleNumberKeyword_8_0; }
		
		//vehicleNumber=EString
		public Assignment getVehicleNumberAssignment_8_1() { return cVehicleNumberAssignment_8_1; }
		
		//EString
		public RuleCall getVehicleNumberEStringParserRuleCall_8_1_0() { return cVehicleNumberEStringParserRuleCall_8_1_0; }
		
		//('vehicleType' vehicleType=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'vehicleType'
		public Keyword getVehicleTypeKeyword_9_0() { return cVehicleTypeKeyword_9_0; }
		
		//vehicleType=EString
		public Assignment getVehicleTypeAssignment_9_1() { return cVehicleTypeAssignment_9_1; }
		
		//EString
		public RuleCall getVehicleTypeEStringParserRuleCall_9_1_0() { return cVehicleTypeEStringParserRuleCall_9_1_0; }
		
		//('customerservice' customerservice=[CustomerService|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'customerservice'
		public Keyword getCustomerserviceKeyword_10_0() { return cCustomerserviceKeyword_10_0; }
		
		//customerservice=[CustomerService|EString]
		public Assignment getCustomerserviceAssignment_10_1() { return cCustomerserviceAssignment_10_1; }
		
		//[CustomerService|EString]
		public CrossReference getCustomerserviceCustomerServiceCrossReference_10_1_0() { return cCustomerserviceCustomerServiceCrossReference_10_1_0; }
		
		//EString
		public RuleCall getCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1() { return cCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1; }
		
		//('customer' customer=[Customer|EString])?
		public Group getGroup_11() { return cGroup_11; }
		
		//'customer'
		public Keyword getCustomerKeyword_11_0() { return cCustomerKeyword_11_0; }
		
		//customer=[Customer|EString]
		public Assignment getCustomerAssignment_11_1() { return cCustomerAssignment_11_1; }
		
		//[Customer|EString]
		public CrossReference getCustomerCustomerCrossReference_11_1_0() { return cCustomerCustomerCrossReference_11_1_0; }
		
		//EString
		public RuleCall getCustomerCustomerEStringParserRuleCall_11_1_0_1() { return cCustomerCustomerEStringParserRuleCall_11_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class RestaurantManagerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.RestaurantManager");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRestaurantManagerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRestaurantManagerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsernameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUsernameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUsernameEStringParserRuleCall_4_1_0 = (RuleCall)cUsernameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPasswordKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPasswordAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_5_1_0 = (RuleCall)cPasswordAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIdAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_6_1_0 = (RuleCall)cIdAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhoneNumberKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhoneNumberAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhoneNumberEStringParserRuleCall_7_1_0 = (RuleCall)cPhoneNumberAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAddressKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAddressAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_8_1_0 = (RuleCall)cAddressAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCuisineKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cCuisineAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cCuisineEStringParserRuleCall_9_1_0 = (RuleCall)cCuisineAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCustomerserviceKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCustomerserviceAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cCustomerserviceCustomerServiceCrossReference_10_1_0 = (CrossReference)cCustomerserviceAssignment_10_1.eContents().get(0);
		private final RuleCall cCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1 = (RuleCall)cCustomerserviceCustomerServiceCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//RestaurantManager returns RestaurantManager:
		//    {RestaurantManager}
		//    'RestaurantManager'
		//    name=EString
		//    '{'
		//        ('username' username=EString)?
		//        ('password' password=EString)?
		//        ('id' id=EInt)?
		//        ('phoneNumber' phoneNumber=EString)?
		//        ('address' address=EString)?
		//        ('cuisine' cuisine=EString)?
		//        ('customerservice' customerservice=[CustomerService|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RestaurantManager}
		//'RestaurantManager'
		//name=EString
		//'{'
		//    ('username' username=EString)?
		//    ('password' password=EString)?
		//    ('id' id=EInt)?
		//    ('phoneNumber' phoneNumber=EString)?
		//    ('address' address=EString)?
		//    ('cuisine' cuisine=EString)?
		//    ('customerservice' customerservice=[CustomerService|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{RestaurantManager}
		public Action getRestaurantManagerAction_0() { return cRestaurantManagerAction_0; }
		
		//'RestaurantManager'
		public Keyword getRestaurantManagerKeyword_1() { return cRestaurantManagerKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('username' username=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'username'
		public Keyword getUsernameKeyword_4_0() { return cUsernameKeyword_4_0; }
		
		//username=EString
		public Assignment getUsernameAssignment_4_1() { return cUsernameAssignment_4_1; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_4_1_0() { return cUsernameEStringParserRuleCall_4_1_0; }
		
		//('password' password=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'password'
		public Keyword getPasswordKeyword_5_0() { return cPasswordKeyword_5_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_5_1() { return cPasswordAssignment_5_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_5_1_0() { return cPasswordEStringParserRuleCall_5_1_0; }
		
		//('id' id=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'id'
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }
		
		//id=EInt
		public Assignment getIdAssignment_6_1() { return cIdAssignment_6_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_6_1_0() { return cIdEIntParserRuleCall_6_1_0; }
		
		//('phoneNumber' phoneNumber=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'phoneNumber'
		public Keyword getPhoneNumberKeyword_7_0() { return cPhoneNumberKeyword_7_0; }
		
		//phoneNumber=EString
		public Assignment getPhoneNumberAssignment_7_1() { return cPhoneNumberAssignment_7_1; }
		
		//EString
		public RuleCall getPhoneNumberEStringParserRuleCall_7_1_0() { return cPhoneNumberEStringParserRuleCall_7_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'address'
		public Keyword getAddressKeyword_8_0() { return cAddressKeyword_8_0; }
		
		//address=EString
		public Assignment getAddressAssignment_8_1() { return cAddressAssignment_8_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_8_1_0() { return cAddressEStringParserRuleCall_8_1_0; }
		
		//('cuisine' cuisine=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'cuisine'
		public Keyword getCuisineKeyword_9_0() { return cCuisineKeyword_9_0; }
		
		//cuisine=EString
		public Assignment getCuisineAssignment_9_1() { return cCuisineAssignment_9_1; }
		
		//EString
		public RuleCall getCuisineEStringParserRuleCall_9_1_0() { return cCuisineEStringParserRuleCall_9_1_0; }
		
		//('customerservice' customerservice=[CustomerService|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'customerservice'
		public Keyword getCustomerserviceKeyword_10_0() { return cCustomerserviceKeyword_10_0; }
		
		//customerservice=[CustomerService|EString]
		public Assignment getCustomerserviceAssignment_10_1() { return cCustomerserviceAssignment_10_1; }
		
		//[CustomerService|EString]
		public CrossReference getCustomerserviceCustomerServiceCrossReference_10_1_0() { return cCustomerserviceCustomerServiceCrossReference_10_1_0; }
		
		//EString
		public RuleCall getCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1() { return cCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class CustomerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.rm2pt.sample.foodapp.Dsl.Customer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCustomerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCustomerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsernameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUsernameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUsernameEStringParserRuleCall_4_1_0 = (RuleCall)cUsernameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPasswordKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPasswordAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_5_1_0 = (RuleCall)cPasswordAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIdAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_6_1_0 = (RuleCall)cIdAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPhoneNumberKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPhoneNumberAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPhoneNumberEStringParserRuleCall_7_1_0 = (RuleCall)cPhoneNumberAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAddressKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAddressAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAddressEStringParserRuleCall_8_1_0 = (RuleCall)cAddressAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cEmailKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cEmailAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cEmailEStringParserRuleCall_9_1_0 = (RuleCall)cEmailAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCustomerserviceKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCustomerserviceAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cCustomerserviceCustomerServiceCrossReference_10_1_0 = (CrossReference)cCustomerserviceAssignment_10_1.eContents().get(0);
		private final RuleCall cCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1 = (RuleCall)cCustomerserviceCustomerServiceCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cDeliverydriverKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cDeliverydriverAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cDeliverydriverDeliveryDriverCrossReference_11_1_0 = (CrossReference)cDeliverydriverAssignment_11_1.eContents().get(0);
		private final RuleCall cDeliverydriverDeliveryDriverEStringParserRuleCall_11_1_0_1 = (RuleCall)cDeliverydriverDeliveryDriverCrossReference_11_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Customer returns Customer:
		//    {Customer}
		//    'Customer'
		//    name=EString
		//    '{'
		//        ('username' username=EString)?
		//        ('password' password=EString)?
		//        ('id' id=EInt)?
		//        ('phoneNumber' phoneNumber=EString)?
		//        ('address' address=EString)?
		//        ('email' email=EString)?
		//        ('customerservice' customerservice=[CustomerService|EString])?
		//        ('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Customer}
		//'Customer'
		//name=EString
		//'{'
		//    ('username' username=EString)?
		//    ('password' password=EString)?
		//    ('id' id=EInt)?
		//    ('phoneNumber' phoneNumber=EString)?
		//    ('address' address=EString)?
		//    ('email' email=EString)?
		//    ('customerservice' customerservice=[CustomerService|EString])?
		//    ('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Customer}
		public Action getCustomerAction_0() { return cCustomerAction_0; }
		
		//'Customer'
		public Keyword getCustomerKeyword_1() { return cCustomerKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('username' username=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'username'
		public Keyword getUsernameKeyword_4_0() { return cUsernameKeyword_4_0; }
		
		//username=EString
		public Assignment getUsernameAssignment_4_1() { return cUsernameAssignment_4_1; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_4_1_0() { return cUsernameEStringParserRuleCall_4_1_0; }
		
		//('password' password=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'password'
		public Keyword getPasswordKeyword_5_0() { return cPasswordKeyword_5_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_5_1() { return cPasswordAssignment_5_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_5_1_0() { return cPasswordEStringParserRuleCall_5_1_0; }
		
		//('id' id=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'id'
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }
		
		//id=EInt
		public Assignment getIdAssignment_6_1() { return cIdAssignment_6_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_6_1_0() { return cIdEIntParserRuleCall_6_1_0; }
		
		//('phoneNumber' phoneNumber=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'phoneNumber'
		public Keyword getPhoneNumberKeyword_7_0() { return cPhoneNumberKeyword_7_0; }
		
		//phoneNumber=EString
		public Assignment getPhoneNumberAssignment_7_1() { return cPhoneNumberAssignment_7_1; }
		
		//EString
		public RuleCall getPhoneNumberEStringParserRuleCall_7_1_0() { return cPhoneNumberEStringParserRuleCall_7_1_0; }
		
		//('address' address=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'address'
		public Keyword getAddressKeyword_8_0() { return cAddressKeyword_8_0; }
		
		//address=EString
		public Assignment getAddressAssignment_8_1() { return cAddressAssignment_8_1; }
		
		//EString
		public RuleCall getAddressEStringParserRuleCall_8_1_0() { return cAddressEStringParserRuleCall_8_1_0; }
		
		//('email' email=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'email'
		public Keyword getEmailKeyword_9_0() { return cEmailKeyword_9_0; }
		
		//email=EString
		public Assignment getEmailAssignment_9_1() { return cEmailAssignment_9_1; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_9_1_0() { return cEmailEStringParserRuleCall_9_1_0; }
		
		//('customerservice' customerservice=[CustomerService|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'customerservice'
		public Keyword getCustomerserviceKeyword_10_0() { return cCustomerserviceKeyword_10_0; }
		
		//customerservice=[CustomerService|EString]
		public Assignment getCustomerserviceAssignment_10_1() { return cCustomerserviceAssignment_10_1; }
		
		//[CustomerService|EString]
		public CrossReference getCustomerserviceCustomerServiceCrossReference_10_1_0() { return cCustomerserviceCustomerServiceCrossReference_10_1_0; }
		
		//EString
		public RuleCall getCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1() { return cCustomerserviceCustomerServiceEStringParserRuleCall_10_1_0_1; }
		
		//('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
		public Group getGroup_11() { return cGroup_11; }
		
		//'deliverydriver'
		public Keyword getDeliverydriverKeyword_11_0() { return cDeliverydriverKeyword_11_0; }
		
		//deliverydriver=[DeliveryDriver|EString]
		public Assignment getDeliverydriverAssignment_11_1() { return cDeliverydriverAssignment_11_1; }
		
		//[DeliveryDriver|EString]
		public CrossReference getDeliverydriverDeliveryDriverCrossReference_11_1_0() { return cDeliverydriverDeliveryDriverCrossReference_11_1_0; }
		
		//EString
		public RuleCall getDeliverydriverDeliveryDriverEStringParserRuleCall_11_1_0_1() { return cDeliverydriverDeliveryDriverEStringParserRuleCall_11_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	
	
	private final UserBaseElements pUserBase;
	private final UserElements pUser;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final CustomerServiceElements pCustomerService;
	private final DeliveryDriverElements pDeliveryDriver;
	private final RestaurantManagerElements pRestaurantManager;
	private final CustomerElements pCustomer;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUserBase = new UserBaseElements();
		this.pUser = new UserElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pCustomerService = new CustomerServiceElements();
		this.pDeliveryDriver = new DeliveryDriverElements();
		this.pRestaurantManager = new RestaurantManagerElements();
		this.pCustomer = new CustomerElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.rm2pt.sample.foodapp.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//UserBase returns UserBase:
	//    {UserBase}
	//    'UserBase'
	//    '{'
	//        ('users' '{' users+=User ( "," users+=User)* '}' )?
	//    '}';
	public UserBaseElements getUserBaseAccess() {
		return pUserBase;
	}
	
	public ParserRule getUserBaseRule() {
		return getUserBaseAccess().getRule();
	}
	
	//User returns User:
	//    CustomerService | DeliveryDriver | RestaurantManager | Customer;
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//CustomerService returns CustomerService:
	//    {CustomerService}
	//    'CustomerService'
	//    name=EString
	//    '{'
	//        ('username' username=EString)?
	//        ('password' password=EString)?
	//        ('id' id=EInt)?
	//        ('phoneNumber' phoneNumber=EString)?
	//        ('restaurantmanager' restaurantmanager=[RestaurantManager|EString])?
	//        ('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
	//        ('customer' customer=[Customer|EString])?
	//    '}';
	public CustomerServiceElements getCustomerServiceAccess() {
		return pCustomerService;
	}
	
	public ParserRule getCustomerServiceRule() {
		return getCustomerServiceAccess().getRule();
	}
	
	//DeliveryDriver returns DeliveryDriver:
	//    {DeliveryDriver}
	//    'DeliveryDriver'
	//    name=EString
	//    '{'
	//        ('username' username=EString)?
	//        ('password' password=EString)?
	//        ('id' id=EInt)?
	//        ('phoneNumber' phoneNumber=EString)?
	//        ('vehicleNumber' vehicleNumber=EString)?
	//        ('vehicleType' vehicleType=EString)?
	//        ('customerservice' customerservice=[CustomerService|EString])?
	//        ('customer' customer=[Customer|EString])?
	//    '}';
	public DeliveryDriverElements getDeliveryDriverAccess() {
		return pDeliveryDriver;
	}
	
	public ParserRule getDeliveryDriverRule() {
		return getDeliveryDriverAccess().getRule();
	}
	
	//RestaurantManager returns RestaurantManager:
	//    {RestaurantManager}
	//    'RestaurantManager'
	//    name=EString
	//    '{'
	//        ('username' username=EString)?
	//        ('password' password=EString)?
	//        ('id' id=EInt)?
	//        ('phoneNumber' phoneNumber=EString)?
	//        ('address' address=EString)?
	//        ('cuisine' cuisine=EString)?
	//        ('customerservice' customerservice=[CustomerService|EString])?
	//    '}';
	public RestaurantManagerElements getRestaurantManagerAccess() {
		return pRestaurantManager;
	}
	
	public ParserRule getRestaurantManagerRule() {
		return getRestaurantManagerAccess().getRule();
	}
	
	//Customer returns Customer:
	//    {Customer}
	//    'Customer'
	//    name=EString
	//    '{'
	//        ('username' username=EString)?
	//        ('password' password=EString)?
	//        ('id' id=EInt)?
	//        ('phoneNumber' phoneNumber=EString)?
	//        ('address' address=EString)?
	//        ('email' email=EString)?
	//        ('customerservice' customerservice=[CustomerService|EString])?
	//        ('deliverydriver' deliverydriver=[DeliveryDriver|EString])?
	//    '}';
	public CustomerElements getCustomerAccess() {
		return pCustomer;
	}
	
	public ParserRule getCustomerRule() {
		return getCustomerAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
